import type { FullPortfolio } from "@shared/schema";

export const portfolioData: FullPortfolio = {
  profile: {
    name: "Arshad Ahmad",
    title: "Cloud & DevOps Engineer",
    tagline: "Building scalable cloud infrastructure and automating deployments",
    bio: "2+ years of experience in full-stack development and DevOps practices, passionate about creating efficient, reliable systems.",
    email: "your.email@example.com",
    linkedIn: "https://linkedin.com/in/yourprofile",
    github: "https://github.com/yourusername",
    twitter: "https://twitter.com/yourhandle",
    resumeUrl: "#",
    profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    techStack: ["AWS", "Docker", "Kubernetes", "Terraform", "React", "Node.js"],
    yearsExperience: 2,
  },
  experiences: [
    {
      id: "1",
      role: "Cloud & DevOps Engineer",
      company: "Tech Company Inc.",
      duration: "2023 - Present",
      description: "Leading cloud infrastructure and DevOps practices for enterprise applications.",
      achievements: [
        "Reduced deployment time by 60% through CI/CD pipeline optimization",
        "Implemented Kubernetes clusters serving 1M+ daily requests",
        "Automated infrastructure provisioning using Terraform and Ansible",
      ],
      techStack: ["AWS", "Kubernetes", "Terraform", "Docker", "GitHub Actions"],
    },
    {
      id: "2",
      role: "Full Stack Developer",
      company: "Startup XYZ",
      duration: "2022 - 2023",
      description: "Developed and maintained scalable web applications from concept to deployment.",
      achievements: [
        "Built responsive web applications serving 50k+ monthly users",
        "Designed RESTful APIs and microservices architecture",
        "Mentored junior developers and conducted code reviews",
      ],
      techStack: ["React", "Node.js", "PostgreSQL", "Redis", "Docker"],
    },
    {
      id: "3",
      role: "Junior Developer",
      company: "Digital Agency",
      duration: "2021 - 2022",
      description: "Started my journey in software development, building client websites and web apps.",
      achievements: [
        "Delivered 10+ client projects on time and within budget",
        "Learned best practices in agile development and version control",
        "Contributed to open-source projects and internal tooling",
      ],
      techStack: ["JavaScript", "React", "CSS", "Git", "Linux"],
    },
  ],
  projects: [
    {
      id: "1",
      title: "Cloud Infrastructure Automation",
      description: "Automated AWS infrastructure provisioning using Terraform and Ansible. Includes VPC, EKS clusters, RDS, and monitoring with CloudWatch.",
      image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=340&fit=crop",
      techStack: ["Terraform", "AWS", "Ansible", "Python"],
      githubUrl: "#",
      liveUrl: "#",
    },
    {
      id: "2",
      title: "Kubernetes Deployment Platform",
      description: "Built a self-service deployment platform for developers to deploy applications to Kubernetes with CI/CD integration and GitOps workflow.",
      image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=340&fit=crop",
      techStack: ["Kubernetes", "ArgoCD", "Helm", "Go"],
      githubUrl: "#",
    },
    {
      id: "3",
      title: "Real-time Analytics Dashboard",
      description: "Full-stack web application for real-time data visualization with WebSocket streaming and responsive charts.",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=340&fit=crop",
      techStack: ["React", "Node.js", "PostgreSQL", "Redis"],
      githubUrl: "#",
      liveUrl: "#",
    },
    {
      id: "4",
      title: "Microservices E-commerce API",
      description: "Scalable e-commerce backend with microservices architecture, event-driven communication, and containerized deployment.",
      image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=340&fit=crop",
      techStack: ["Node.js", "Docker", "RabbitMQ", "MongoDB"],
      githubUrl: "#",
    },
  ],
  skills: [
    { name: "AWS", category: "cloud" },
    { name: "IBM Cloud", category: "cloud" },
    { name: "Docker", category: "devops" },
    { name: "Kubernetes", category: "devops" },
    { name: "Jenkins", category: "devops" },
    { name: "GitHub Actions", category: "devops" },
    { name: "Prometheus", category: "devops" },
    { name: "Grafana", category: "devops" },
    { name: "Terraform", category: "cloud" },
    { name: "React", category: "development" },
    { name: "Node.js", category: "development" },
    { name: "TypeScript", category: "development" },
    { name: "Python", category: "development" },
    { name: "PostgreSQL", category: "tools" },
    { name: "MongoDB", category: "tools" },
    { name: "Linux", category: "tools" },
  ],
};
